### ISSUE TITLE
Failed to activate the ng-classify-preview package

### ISSUE THREAD

**Issue by escargotprodige** [CaryLandholt/atom-ng-classify-preview#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: linux 3.19.4-200.fc21.x86_64
**Thrown From**: [ng-classify-preview](https://github.com/CaryLandholt/atom-ng-classify-preview) package, v0.2.1
### Stack Trace

Failed to activate the ng-classify-preview package

```
At Cannot find module '/usr/share/atom/resources/app.asar/src/editor'

Error: Cannot find module '/usr/share/atom/resources/app.asar/src/editor'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/CleverCoding/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:5:16)
  at Object.<anonymous> (/home/CleverCoding/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/CleverCoding/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:15)
  at Object.<anonymous> (/home/CleverCoding/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:677:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:239:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:218:14)
  at /usr/share/atom/resources/app.asar/src/package.js:740:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:219:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -0:03.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.1.0 core:move-down (atom-text-editor.editor.mini)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.7.0 ng-classify-preview:coffee (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "open-last-project"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v4.0.8
atom-yeoman, v0.1.5
autocomplete-plus, v2.12.0
color-picker, v1.7.0
docblockr, v0.6.3
flow, v0.4.0
haxe, v0.6.1
indent-guide-improved, v1.1.1
language-haxe, v0.2.1
language-jade, v0.4.0
linter, v0.12.1
ng-classify-preview, v0.2.1
project-manager, v1.15.5
vim-mode, v0.44.0

# Dev
No dev packages
```

**Comment by CaryLandholt** [comment]
This package has been deprecated.
See the [README](https://github.com/CaryLandholt/atom-ng-classify-preview/blob/master/README.md) for alternatives.

Thanks,
Cary
