### ISSUE TITLE
Uncaught Error: Cannot find module '/usr/share/atom/resources/app.asar/src/editor'

### ISSUE THREAD

**Issue by meataur** [CaryLandholt/atom-ng-classify-preview#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: "Fedora release
**Thrown From**: [ng-classify-preview](https://github.com/CaryLandholt/atom-ng-classify-preview) package, v0.2.1
### Stack Trace

Uncaught Error: Cannot find module '/usr/share/atom/resources/app.asar/src/editor'

```
At module.js:330

Error: Cannot find module '/usr/share/atom/resources/app.asar/src/editor'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ataur/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:5:16)
  at Object.<anonymous> (/home/ataur/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ataur/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:15)
  at Object.<anonymous> (/home/ataur/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
  4x -9:59.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 16x -7:11.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 14x -5:19.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:34.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -1:58.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 14x -1:10.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
angularjs-boilerplate-snippets, v0.3.1
angularjs-snippets, v0.10.17
angularjs-styleguide-snippets, v0.7.0
atom-html-preview, v0.1.8
atom-ternjs, v0.6.6
autoclose-html, v0.18.0
codeigniter, v0.1.3
data-atom, v0.6.1
emmet, v2.3.10
emmet-simplified, v2.4.2
html-entities, v0.4.0
html-id-class-snippets, v1.4.1
htmlhint, v1.1.3
js-patterns-atom-snippets, v0.2.1
language-html-swig, v2.0.0
language-html5-subtlegradient, v0.1.0
language-sql-mysql, v0.3.1

# Dev
No dev packages
```

**Comment by CaryLandholt** [comment]
This package has been deprecated.
See the [README](https://github.com/CaryLandholt/atom-ng-classify-preview/blob/master/README.md) for alternatives.

Thanks,
Cary
