### ISSUE TITLE
Uncaught Error: Cannot find module 'C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\a...

### ISSUE THREAD

**Issue by BobBuford** [CaryLandholt/atom-ng-classify-preview#4]
[Enter steps to reproduce below:]
1. ...install Atom from AtomSetup.exe
2. ...install package ng-classify-preview package from within Atom

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [ng-classify-preview](https://github.com/CaryLandholt/atom-ng-classify-preview) package, v0.2.1
### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\editor'

```
At module.js:336

Error: Cannot find module 'C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\editor'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\bob.buford\.atom\packages\ng-classify-preview\lib\NgClassifyPreviewView.coffee:5:16)
  at Object.<anonymous> (C:\Users\bob.buford\.atom\packages\ng-classify-preview\lib\NgClassifyPreviewView.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\bob.buford\.atom\packages\ng-classify-preview\lib\ng-classify-preview.coffee:1:15)
  at Object.<anonymous> (C:\Users\bob.buford\.atom\packages\ng-classify-preview\lib\ng-classify-preview.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:168:21)
  at C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:588:27)
  at C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:379:26
  at exit (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -5:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -3:10.4.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
     -1:54.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -1:43.5.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
angular-jonpapa-snippets, v0.7.0
angularjs, v0.3.3
angularjs-boilerplate-snippets, v0.3.1
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.2
atometer, v0.1.0
autocomplete-angular-material, v0.4.0
emmet, v2.3.13
emmet-simplified, v2.5.0
emmet-snippets-compatibility, v1.0.0
fold-comments, v0.5.0
language-coffee-script-angular, v2.2.0
php-extract-method, v0.2.0
standard-angularjs-snippets, v0.1.1

# Dev
No dev packages
```

**Comment by CaryLandholt** [comment]
This package has been deprecated.
See the [README](https://github.com/CaryLandholt/atom-ng-classify-preview/blob/master/README.md) for alternatives.

Thanks,
Cary
