### ISSUE TITLE
Failed to load the ng-classify-preview package

### ISSUE THREAD

**Issue by pelted** [CaryLandholt/atom-ng-classify-preview#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.2
**Thrown From**: [ng-classify-preview](https://github.com/CaryLandholt/atom-ng-classify-preview) package, v0.2.1
### Stack Trace

Failed to load the ng-classify-preview package

```
At Cannot find module '/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/editor'

Error: Cannot find module '/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/editor'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/chris/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:5:16)
  at Object.<anonymous> (/Users/chris/.atom/packages/ng-classify-preview/lib/NgClassifyPreviewView.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/chris/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:15)
  at Object.<anonymous> (/Users/chris/.atom/packages/ng-classify-preview/lib/ng-classify-preview.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/package-manager.js:473:30)
  at /opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -0:44.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.9.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  3x -0:43.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:38.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:37.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:36.7.0 application:minimize (atom-text-editor.editor.is-focused)
     -0:27.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:20.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:18.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:18.2.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "wrap-guide",
      "placeholder-text"
    ],
    "projectHome": "/Users/chris/code",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".tag*"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner-ruby, v1.4.0
angularjs, v0.3.3
api-blueprint-preview, v0.6.0
atom-alignment, v0.12.1
atom-beautify, v0.28.17
atom-ctags, v4.4.0
autocomplete-ruby, v0.1.0
build, v0.48.0
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
git-log, v0.4.1
grunt-runner, v0.11.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
html-entities, v0.4.0
imdone-atom, v1.1.54
javascript-snippets, v1.0.0
language-api-blueprint, v1.0.2
language-nginx, v0.6.1
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-less, v2.2.0
linter-ruby, v1.2.0
linter-scss-lint, v2.4.0
linter-tidy, v1.0.1
minimap, v4.16.0
ng-classify-preview, v0.2.1
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
rails-model-schema, v0.6.0
remote-atom, v1.2.9
ruby-block, v0.3.5
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by benaubin** [comment]
Got this error, too.

**Comment by CaryLandholt** [comment]
Hi @pelted and @penne12,

ng-classify is now supported in https://atom.io/packages/preview, which is a generic viewer of multiple file types, including ng-classify.

Hope this helps.

Thanks,
Cary

**Comment by benaubin** [comment]
@CaryLandholt Ok, thanks! You might want to mark this package as deprecated so people don't load it. I still like the snippets it comes with, could you please export those for us?

**Comment by CaryLandholt** [comment]
Thanks @penne12 - I've deprecated the package.

**Comment by CaryLandholt** [comment]
THIS PACKAGE HAS BEEN DEPRECATED

> Please use [preview](https://atom.io/packages/preview) for previewing your ng-classify files
> Please use [ng-classify-snippets](https://github.com/CaryLandholt/atom-ng-classify-snippets) for convenient keyboard shortcuts

**Comment by benaubin** [comment]
Thanks so much!
